nodeLinker: node-modules

npmRegistries:
  "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/":
    npmAuthToken: "${NPM_AUTH_TOKEN}"

npmScopes:
  codefi:
    npmRegistryServer: "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/"
