nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NPM_AUTH_TOKEN}"

npmScopes:
  metamask-private:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "${NPM_AUTH_TOKEN}"