nodeLinker: node-modules

npmRegistries:
  "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/":
    npmAuthToken: "NpmToken.d51a305f-04bc-389f-aa4d-ac9d1c922997"

npmScopes:
  codefi:
    npmRegistryServer: "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/"
